### ISSUE TITLE
Let users edit their settings in the UI

### ISSUE THREAD

**Issue by jyasskin** [jyasskin/sidewalk-obstruction-bingo#12]
The choice to share reports at all, and to automatically use the device's current location, should have checkboxes in the UI.

@clvlach to create the checkboxes in the first place, and then I'll wire them up.

**Comment by clvlach** [comment]
Switches created in "How to Play" section.

**Comment by jyasskin** [comment]
And wired up in 9d45f334889d52ad9d8891ef9ac9502ec731a228.
