### ISSUE TITLE
Make a favicon

### ISSUE THREAD

**Issue by jyasskin** [jyasskin/sidewalk-obstruction-bingo#3]
https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/rel#attr-icon

**Comment by clvlach** [comment]
Use Oregon Walks favicon.

**Comment by jyasskin** [comment]
It turns out that we need a 192x192 PNG and ideally a 512x512 PNG, as described in https://web.dev/installable-manifest/. I've added the Oregon Walks 100x82 (??) PNG to https://github.com/jyasskin/sidewalk-obstruction-bingo/blob/main/public/manifest.webmanifest#L8, but it'd be good to have the right sizes.
