### ISSUE TITLE
Flow of questions for location sharing pop-up

### ISSUE THREAD

**Issue by clvlach** [jyasskin/sidewalk-obstruction-bingo#5]
- When you get your first tile, pop-up box asks “Do you want to share the location of the obstructions you find with OW? Sharing the location will allow us to better advocate for obstacle-free sidewalks. Yes/No” 

- If no, mark obstacle as found. Ask again when the board is reshuffled? We should still record the fact that the obstacle was found. 

- If yes, request location info. Add checkbox option to “always use current location.” Or maybe auto fill current location? Want to minimize number of buttons to click.

**Comment by jyasskin** [comment]
Could you check it now, and see what still ought to change?
